# Phase 2: Data Cleaning

## Objective

The objective of this notebook is to clean the datasets before performing analysis and forecasting.

Tasks:

- Check missing values
- Check duplicate records
- Verify data types
- Convert date columns
- Remove duplicate records (if any)
- Validate numerical columns

In [2]:
# Import Libraries

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [3]:
import pandas as pd

sales = pd.read_csv("../data/raw/sales_transactions.csv")

sku = pd.read_csv("../data/raw/sku_master.csv")

inventory = pd.read_csv("../data/raw/inventory_snapshot.csv")

# Missing Values Analysis

In [4]:
print("Sales Missing Values")

sales.isnull().sum()

Sales Missing Values

date                  0
receipt_id            0
store_id              0
sku_id                0
customer_id           0
quantity              0
unit_price            0
total_value           0
channel               0
discount_pct          0
promo_id        7881687
dtype: int64

In [5]:
print("SKU Missing Values")

sku.isnull().sum()

SKU Missing Values

sku_id         0
sku_name       0
category       0
subcategory    0
unit_price     0
cost_price     0
brand          0
dtype: int64

In [6]:
print("Inventory Missing Values")

inventory.isnull().sum()

Inventory Missing Values

store_id             0
sku_id               0
stock_on_hand        0
reorder_point        0
safety_stock         0
last_restock_date    0
dtype: int64

# Duplicate Records

In [7]:
print("Sales Duplicate Records")

print(sales.duplicated().sum())

Sales Duplicate Records

13019

In [8]:
print("SKU Duplicate Records")

print(sku.duplicated().sum())

SKU Duplicate Records
0

In [9]:
print("Inventory Duplicate Records")

print(inventory.duplicated().sum())

Inventory Duplicate Records
0

# Remove Duplicate Records

In [10]:
sales = sales.drop_duplicates()

sku = sku.drop_duplicates()

inventory = inventory.drop_duplicates()

print("Duplicate Records Removed")

Duplicate Records Removed

# Data Types Verification

In [11]:
sales.dtypes

date                str
receipt_id          str
store_id            str
sku_id              str
customer_id         str
quantity          int64
unit_price      float64
total_value     float64
channel             str
discount_pct    float64
promo_id            str
dtype: object

In [12]:
sku.dtypes

sku_id             str
sku_name           str
category           str
subcategory        str
unit_price     float64
cost_price     float64
brand              str
dtype: object

In [13]:
inventory.dtypes

store_id               str
sku_id                 str
stock_on_hand        int64
reorder_point        int64
safety_stock         int64
last_restock_date      str
dtype: object

# Convert Date Columns

In [14]:
sales["date"] = pd.to_datetime(sales["date"])

inventory["last_restock_date"] = pd.to_datetime(
    inventory["last_restock_date"]
)

print("Date Columns Converted Successfully")

Date Columns Converted Successfully

# Verify Converted Data Types

In [15]:
sales.dtypes

date            datetime64[us]
receipt_id                 str
store_id                   str
sku_id                     str
customer_id                str
quantity                 int64
unit_price             float64
total_value            float64
channel                    str
discount_pct           float64
promo_id                   str
dtype: object

In [16]:
inventory.dtypes

store_id                        str
sku_id                          str
stock_on_hand                 int64
reorder_point                 int64
safety_stock                  int64
last_restock_date    datetime64[us]
dtype: object

# Check Numeric Columns

In [17]:
sales.describe()

,date,quantity,unit_price,total_value,discount_pct
count,9959019,9.959019e+06,9.959019e+06,9.959019e+06,9.959019e+06
mean,2024-02-06 14:22:07.214336,1.881009e+00,6.213040e+02,1.094777e+03,6.274108e+00
min,2022-01-01 00:00:00,1.000000e+00,2.441000e+01,1.225000e+01,0.000000e+00
25%,2023-02-06 00:00:00,1.000000e+00,1.734300e+02,2.350200e+02,0.000000e+00
50%,2024-02-15 00:00:00,2.000000e+00,3.363100e+02,5.427900e+02,0.000000e+00
75%,2025-01-31 00:00:00,3.000000e+00,9.163800e+02,1.277610e+03,0.000000e+00
max,2025-12-31 00:00:00,5.000000e+00,4.755470e+03,2.377735e+04,4.980000e+01
std,NaN,1.089339e+00,6.753029e+02,1.537465e+03,1.381917e+01

In [18]:
inventory.describe()

       stock_on_hand  reorder_point  safety_stock           last_restock_date
count   21228.000000   21228.000000  21228.000000                       21228
mean      154.978566      59.906774     20.920859  2025-09-16 23:56:20.214810
min         0.000000      20.000000      4.000000         2025-05-06 00:00:00
25%        40.000000      39.000000     13.000000         2025-07-14 00:00:00
50%       125.000000      60.000000     20.000000         2025-09-12 00:00:00
75%       240.000000      80.000000     27.000000         2025-11-27 00:00:00
max       600.000000     100.000000     50.000000         2025-12-31 00:00:00
std       135.183820      23.376075      9.875016                         NaN

# Data Quality Summary

Cleaning activities completed:

- Checked missing values
- Checked duplicate records
- Removed duplicate rows
- Converted date columns
- Verified numerical columns

The datasets are now ready for Exploratory Data Analysis (EDA).

In [ ]:
# =====================================================
# CREATE GITHUB FRIENDLY SAMPLE DATASETS
# =====================================================

import pandas as pd

# Sample only sales dataset
sales_sample = sales.sample(
    n=100000,
    random_state=42
)

# SKU & Inventory already comparatively small
sku_sample = sku.copy()
inventory_sample = inventory.copy()

# Save processed datasets

sales_sample.to_csv(
    "../data/processed/sales_clean.csv",
    index=False
)

sku_sample.to_csv(
    "../data/processed/sku_clean.csv",
    index=False
)

inventory_sample.to_csv(
    "../data/processed/inventory_clean.csv",
    index=False
)

print("="*60)
print("✅ Sample datasets created successfully")
print("="*60)

print("Sales Rows :", len(sales_sample))
print("SKU Rows :", len(sku_sample))
print("Inventory Rows :", len(inventory_sample))

============================================================
✅ Sample datasets created successfully
============================================================
Sales Rows : 100000
SKU Rows : 5000
Inventory Rows : 21228